### ISSUE TITLE
有无考虑内置时钟?

### ISSUE THREAD

**Issue by wewindy** [newbeea/gl-widget#1]
项目很好玩，适合练习，感谢贡献。
示例代码都是定义了一个 `time` uniform，然后每一帧更新 0.01 的样子，略显粗糙，不过直观

**Comment by newbeea** [comment]
> 项目很好玩，适合练习，感谢贡献。
> 示例代码都是定义了一个 `time` uniform，然后每一帧更新 0.01 的样子，略显粗糙，不过直观

这里是想把这个控制权交给使用者，time可以是非线性的来实现其他效果
例子确实想要直观一点
好久没更新了，惭愧
